import Header from "../../../components/header.jsx";
import Link from "next/link";
import styles from "../counsel-accused-video-conference/detail.module.css";

export const metadata = {
  title: "Part - II : The Correct View on S. 173(8) Cr.P.C",
};

const paragraphs = [
  "In the preceding article, titled “Part I – An Incorrect View on S. 173(8) Cr.P.C.”, I had examined the judgments of the Supreme Court in Amruthbhai Shambhubhai Patel v. Sumanbhai Kantibhai Patel and Others, (2017) 4 SCC 177, and Reeta Nag v. State of West Bengal and Others, (2009) 9 SCC 129, and analysed why the view expressed therein does not advance, and is in fact inconsistent with, the legislative intent underlying the introduction of Section 173(8) Cr.P.C.",
  "In this article, I examine the purpose and legislative background leading to the introduction of Section 173(8) Cr.P.C. by the 1973 Amendment, and contend that the power of the Trial Court to direct further investigation extends even to the post-cognizance stage, whether exercised suo motu or at the instance of the Complainant. I then examine certain judgments of the Supreme Court which have taken a view contrary to that expressed in Reeta Nag and Amruthbhai Patel, and explain why such contrary views are more acceptable, having regard to the purpose of criminal investigation and, more particularly, the legislative intent underlying the introduction of Section 173(8).",
  "Let us first examine the purpose and background leading to the introduction of Section 173(8) into the Code of Criminal Procedure. The Forty-first Report of the Law Commission of India on the Code of Criminal Procedure, 1898, considered the issue of reopening an investigation in the context of the then-existing Section 173 of the 1898 Code and made the following recommendation:—",
  "“14.23: A report under Section 173 is normally the end of the investigation. Sometimes, however, the police officer after submitting the report under section 173 comes upon evidence bearing on the guilt or innocence of the accused. We should have thought that the police officer can collect that evidence and send it to the magistrate concerned. It appears, however, that courts have sometimes taken the narrow view that once a final report under section 173 has been sent, the police cannot touch the case again and cannot re-open the investigation. This view places a hindrance in the way of the investigating agency, which can be very unfair to the prosecution and, for that matter, even to the accused. It should be made clear in section 173 that the competent police officer can examine such evidence and send a report to the magistrate. Copies concerning the fresh material must of course be furnished to the accused.”",
  "As could be seen, the Law Commission noted that the Police, after submitting a report under Section 173 Cr.P.C., may come upon further evidence bearing on the guilt or innocence of the Accused. It observed that the narrow view, taken by some courts, that the Police cannot reopen an investigation once the report has been submitted to the Magistrate, could operate unfairly against the prosecution and perhaps equally, against the Accused. One such decision was N. Krishnaswamy & others v/s State, AIR 1956 Mad 592.",
  "The purpose of a criminal investigation is to unearth the truth and place it before the Court with the best possible material in support of the facts so unearthed. If the truth cannot be fully unearthed at the initial stage, the mechanism to discover it ought not to be closed once and for all. This was the intent behind introducing Section 173(8) into the Code. Since the power of investigation is vested in the Police, they were consequently bolstered with the power of further investigation.",
  "The power of the Police to conduct further investigation, perhaps with a formal permission from the Court or by informing the Court, remains undisputed. The seminal issue, therefore, is this: if the Police can reopen an investigation upon unearthing something new after filing the Final Report, what would deter the Courts from directing further investigation when some vital material or circumstance, having great relevance to the case, comes to their knowledge?",
  "Procedurally, upon completion of investigation and filing of the Final Report, the immediate next stage is for the Trial Court to consider cognizance and process. At that stage, the Court is required only to determine whether prima facie material exists, and if so, the offences disclosed and the persons against whom they are made out, and thereafter pass appropriate orders on cognizance and issuance of summons. The Court is not expected at that stage to scrutinise the investigation for its flaws, or to determine whether it is complete, thorough, or supported by the best possible material, though its power at that stage does include directing further investigation upon such appreciation.",
  "The question, therefore, arises: who is better equipped than the trial courts to appreciate the available material in a Report under Section 173 Cr.P.C., or for that matter, to appreciate what is lacking in such Report? No doubt, this exercise commences immediately upon filing of the Final Report, while applying the judicial mind for taking cognizance. But to hold that it comes to an end no sooner cognizance is taken would be to place an unduly restrictive interpretation on the Court’s powers.",
  "Consider a significant and practical scenario. A charge sheet is filed with sufficient material to take cognizance and issue process, and the Magistrate does so. At the same time, the Magistrate may notice an inherent flaw in the investigation—for instance, the failure to send vital material collected during investigation to the Forensic Science Laboratory, or the failure to examine a vital witness whose presence is apparent from a video relied upon as supporting material. In such circumstances, it would defeat the very process of administration of criminal justice to hold that the Magistrate cannot, while taking cognizance, also direct further investigation.",
  "This becomes even more significant where the Accused is in custody and the Report is filed on the 89th day. It would be wholly incongruous for the Magistrate to withhold cognizance and instead direct further investigation, since that would result in the Accused becoming entitled to statutory bail.",
  "While analysing the issue in its entirety, we cannot lose sight of the reality that, upon completing the investigation and filing its Report, the Investigating Agency ordinarily moves on and has no reason to revisit the investigation already concluded, or to continue it, except where further investigation is undertaken for a specific purpose in a given case. As regards the material placed before the Court, it is the Trial Court that is best placed to analyse and appreciate it. Indeed, no other Court is as equipped as the Trial Court to appreciate the investigation material. It is the Court of original jurisdiction before which such material unfolds and where the foundation is laid for determining the guilt or innocence of the Accused. It ought, therefore, to have, or be deemed to have, all necessary powers to ensure a full and thorough investigation so as to facilitate a proper and meaningful trial. Those powers cannot be stifled by reference to the stage at which they are exercised.",
  "In the case of Amrutbhai Patel, in its concluding discussions, the Supreme Court observes, “Not only such power to the Magistrate to direct further investigation suo motu or on the request or prayer of the complainant/informant after cognizance is taken and the accused persons appears, pursuant to the process, issued or is discharged, is incompatible with the statutory design and dispensation, it would even otherwise render the provisions of Sections 311 and 319 Cr.P.C, where-under any witness can be summoned by a Court and a person can be issued notice to stand trial at any stage, in a way redundant.”",
  "The ratio laid above leads to an inference on the position of law that, a need for further investigation, when felt, can be adequately addressed by invoking powers under Section 311 Cr.P.C., i.e., examination of witnesses, or Section 319 Cr.P.C., i.e., addition of an Accused to face trial. It would, however, be a misplaced argument to contend that, where the Police themselves identify the need for further investigation, such need ought to be addressed by invoking Section 173(8) Cr.P.C., since Sections 311 and 319 Cr.P.C. would not effectively meet that need, but where the same need is perceived by the Court suo motu or arises upon an application by the Complainant, the remedy must instead be confined to Sections 311 or 319 Cr.P.C. Such an argument cannot be reconciled with the legislative intent behind introducing Section 173(8) into the Code. It cannot safely or beneficially be interpreted that the Legislature intended to exclude the Courts from invoking Section 173(8) Cr.P.C. post cognizance, while reserving such power only to the Police.",
  "Our criminal justice system has, by far too long, yet to resolutely pursue and protect the interests of victims of crime. More often than not, there is a feeling that the State exhibits a “lackadaisical approach” towards efforts to curb crime. The effective implementation of the law, however, remains essential, and the onus of ensuring the same rests with the Courts. Ensuring a full and thorough investigation leading to a purposeful trial would go a long way towards the successful administration of the criminal justice system.",
  "So, to say that the power of the Magistrate or Trial Courts under Section 173(8) of the Code to direct further investigation, suo motu or at the request or prayer of the Complainant/Informant, after cognizance has been taken and the Accused has appeared pursuant to the process issued or has been discharged, is incompatible with the statutory design and dispensation, would be incorrect. The Supreme Court, in these two cases, i.e., Reeta Nag and Amrutbhai Patel, has, in my respectful view, misinterpreted Section 173(8) Cr.P.C. and misdirected itself.",
  "The Code of Criminal Procedure is an exhaustive Code, but only in respect of matters specifically dealt with by it. The absence of a provision dealing with a particular matter does not, by itself, mean that no such power exists. The Court may proceed on the principle that a procedure should ordinarily be understood as permissible unless it is shown to be prohibited by law, especially considering the legislative intent behind introducing Section 173(8) into the Code. Further, procedural laws cannot be interpreted merely verbatim; an interpretation that furthers the cause of such procedure—namely, the purity of the administration of justice—should find favour with the Courts, more so with Courts of Precedent.",
  "This view—that the Trial Courts and Magistrates possess the power under Section 173(8) Cr.P.C. to direct further investigation post cognizance, suo motu and even on an application by the victim/informant—is supported by several decisions of the Supreme Court. On the strength of these decisions, it can be propounded that Reeta Nag and Amrutbhai Patel were rendered per incuriam. The principle of stare decisis ought to have guided the Supreme Court in both cases to follow the earlier judgments and/or judgments of co-ordinate Benches of larger strength. A brief discussion follows:—",
  "Kishan Lal v/s Dharmendra Bafna (2009) 7 SCC 685 : In this case, the jurisdiction of the Magistrate to direct re-investigation of a case from time to time under Section 173(8) of Cr.P.C. was the question involved. The factual matrix would also indicate that the issue was regarding further investigation post cognizance, on an application filed by the informant.",
  "The line of arguments addressed by two eminent lawyers before the Supreme Court in this matter assumes relevance to the legal position discussed in this article. The arguments addressed by Senior Counsel Mr. K.T.S. Tulsi and Senior Counsel Mr. U.U. Lalit (as he then was) complement each other on the legal position concerning the powers of the Trial Court to direct further investigation after cognizance is taken. While both concurred with the legal position that the learned Magistrate had the requisite jurisdiction to direct further investigation post cognizance, their submissions were in the tenor of it being a settled legal position.",
  "The Supreme Court, while deciding the issue, observes at Para 15:",
  "“An order of further investigation can be made at various stages including the stage of the trial, that is, after taking cognizance of the offence.”",
  "Again, at Para 16, while it is observed that the investigating officer may exercise power under Section 173(8) of Cr.P.C. when new facts come to his notice, it is further observed:",
  "“Apart from the aforementioned grounds, the learned Magistrate or the superior courts can direct further investigation, if the investigation is found to be tainted and/or otherwise unfair or is otherwise necessary in the ends of justice.",
  "Samaj Parivartan Samudaya and others V/s State of Karnataka and others, 2012 (7) SCC 407: This Three Judge Bench judgment of the Supreme Court dealt in detail with the process that follows upon registration of the FIR, leading up to the filing of the Final Report. At Para 27, while discussing what follows upon the laying of the Final Report in the form of charge sheet and cognizance, and the powers of the Magistrate under Section 173(8) of Cr.P.C., the Court observes:",
  "“Thus, under Section 173(8), where charge-sheet has been filed, the court also enjoys the jurisdiction to direct further investigation into the offence.”",
  "Relying on Hemant Dhasmana Vs CBI (2001) 7 SCC 536, it was again observed at Para 37:",
  "“We may notice that the investigation of a case or filing of charge-sheet in a case does not by itself bring the absolute end to exercise of power by the investigating agency or by the court.”",
  "At a later part in the judgment, at Para 55, it was observed:",
  "“It is a settled position of law that an investigating agency is empowered to conduct further investigation after institution of a charge-sheet before the court of competent jurisdiction. A Magistrate is competent to direct further investigation in terms of Section 173(8) Cr.P.C in the case instituted on a police report.”",
  "Further, at Para 56:",
  "“Significantly, it requires to be noticed that when the court is to ensure fair and proper investigation in an adversarial system of criminal administration, the jurisdiction of a court is of a much higher degree than it is an inquisitorial system. It is clearly contemplated under the Indian criminal jurisprudence that an investigation should be fair, in accordance with law and should not be tainted. But, at the same time, the court has to take precaution that interested or influential persons are not able to misdirect or hijack the investigation so as to throttle a fair investigation resulting in the offenders escaping the punitive of course of law. It is the inherent duty of the court and any lapse in this regard would tantamount to error of jurisdiction.”",
  "Vinay Tyagi Vs Irshad Ali alias Deepak and others, (2013) 5 SCC 762: A relatively recent judgment of a Two Judge Bench of the Hon’ble Supreme Court, this case analysed at great length the kinds of investigation contemplated under the Code, namely, initial investigation, further investigation and fresh or de-novo investigation. The Supreme Court, through Justice Swatanter Kumar, speaking for the Bench, notes at Para 30:",
  "“The power of the court to pass an order for further investigation has been a matter of judicial concern for some time. The courts have taken somewhat divergent but not diametrically opposite views in this regard.”",
  "The Court thereafter proceeded to reconcile and harmoniously apply such views, while maintaining fidelity to the rule of precedence. At Para 31, the Court observed that the power to conduct further investigation in terms of Section 173(8) Cr.P.C. is vested even with the trial court, which can direct further investigation even where the report has been filed, and usefully referred to State of Punjab Vs CBI, 2011 (9) SCC 182. The Court further clarified that any doubt regarding a wider interpretation of Section 173(8) stood removed, and the controversy put to an end, by the judgment in Hemant Dhasmana v/s CBI, 2001 (7) SCC 536, wherein it was held that, although the said section does not, in specific terms, mention the power of the court to order further investigation, the power of the police to conduct further investigation envisaged therein can be triggered into motion at the instance of the court.",
  "The judgment in Vinay Tyagi had considered certain contrary views taken by the Supreme Court, including Reeta Nag. However, the Supreme Court ruled that those judgments would have to be examined in light of the principles of stare decisis, for not considering the view taken by the larger Bench in Bhagwant Singh v/s Commissioner of Police, (1985) 2 SCC 537.",
  "In conclusion, after giving a considered thought to the principles stated in several judgements, the Supreme Court in Vinay Tyagi finally observed that the Magistrate before whom a report under Section 173(2) of the Code is filed is empowered in law to direct further investigation. The Court thereafter laid down six specific propositions, including that neither the scheme of the Code nor any specific provision therein bars exercise of such jurisdiction by the Magistrate, and that the language of Section 173(2) cannot be construed so restrictively as to deprive the Magistrate of such powers, particularly in the face of the provision in Section 156(3) and the language of Section 173(8) itself. Such power would, therefore, have to be read into the language of Section 173(8).",
  "It could be well appreciated that, in Vinay Tyagi, while laying down the above propositions, the Court observed that the Code is a procedural document and must receive a construction which would advance the cause of justice and the legislative object sought to be achieved. It does not stand to reason that the legislature provided powers of further investigation to the Police even after filing a report, but intended to curtail the power of the Court to the extent that, even where the facts of the case and ends of justice demand, the Court can still not direct the investigating agency to conduct further investigation which it could do on its own.",
  "I would say that these observations of the Supreme Court ought to clinch the issue and drive home the point that the trial court, post cognizance, is indeed empowered to direct further investigation of its own motion or on the application of the Complainant.",
  "Two other noteworthy cases are Ram Lal Narang Vs State (Delhi Administration), (1979) 2 SCC 322 and H.N. Rishbud and Inder Singh Vs State of Delhi, (1955) 1 SCR 1150 – AIR 1955 SC 196. While H.N. Rishbud is a judgment delivered prior to the introduction of Section 173(8) into the Code, Ram Lal Narang was concerned with further investigation and the powers of the courts in that regard.",
  "In Ram Lal Narang, the Supreme Court, relying upon the judgment of the Three-Judge Bench in H.N. Rishbud, observed:",
  "“It does not follow that the invalidity of the investigation is to be completely ignored by a court during trial. When the breach of such mandatory provision is brought to the knowledge of the court at a sufficiently early stage, the Court, while not declining cognizance, will have to take the necessary steps to get the illegality cured and the defect rectified, by ordering such re-investigation as the circumstances of an individual case may call for (sic) wholly or partly”.",
  "Referring to the above observation in H.N. Rishbud, the Supreme Court further made the position explicit:",
  "“This decision is a clear authority for the view that further investigation is not altogether ruled out merely because cognizance of the case has been taken by the Court; defective investigation coming to light during the course of a trial may be cured by a further investigation, if circumstances permit it”.",
  "Thus, Ram Lal Narang recognised that the taking of cognizance does not, by itself, bring the investigative process to an absolute end. On the contrary, the judgment emphasised, at considerable length, the importance of a complete and proper investigation, the respective powers and functions of the police and the courts in relation to investigation, and the principle that a defect or illegality in investigation, however serious, does not by itself vitiate the cognizance taken or the subsequent trial.",
  "The judgment then considered circumstances in which further investigation may become necessary and, significantly, addressed the course to be adopted by the Magistrate even where cognizance had already been taken. The Court observed:",
  "“In either case, it is for the Magistrate to decide upon his future course of action depending upon the stage at which the case is before him. If he has already taken cognizance of the offence, but has not proceeded with the enquiry or trial, he may direct the issue of process to persons freshly discovered to be involved and deal with all the accused, in a single enquiry or trial. If the case of which he has previously taken cognizance has already proceeded to some extent, he may take fresh cognizance of the offence disclosed against the newly involved accused and proceed with the case as a separate case. What action a Magistrate is to take in accordance with the provision of the Code of Criminal Procedure in such situations is a matter best left to the discretion of the Magistrate.",
  "The criticism that a further investigation by the police would trench upon the proceedings before the Court is really not of very great substance, since whatever the police may do, the final discretion in regard to further action is with the Magistrate. That the final word is with the Magistrate is sufficient safeguard against any excessive use or abuse of the power of the police to make further investigation.",
  "We should not, however, be understood to say that the police should ignore the pendency of a proceeding before a Court and investigate every fresh fact that comes to light as if no cognizance had been taken by the Court of any offence. We think that in the interests of the independence of the magistracy and the judiciary, in the interests of the purity of the administration of criminal justice and in the interests of the comity of the various agencies and institutions entrusted with different stages of such administration, it would ordinarily be desirable that the police should inform the Court and seek formal permission to make further investigation when fresh facts come to light.” (emphasis supplied)",
  "The last observations made, emphasised above, should settle all apprehensions that, there will never be an end to the process of investigation or trial, if every time the courts have to order further investigation, either suo motu or on the application of investigation.",
  "Several High Courts are presently following the ratio laid in Amrutbhai Patel, while binding itself with rules of precedents. Now, whether Amruthbhai Patel is a binding precedent by application of jurisprudence of precedents, is another question. In my opinion, it is not, if the rules of precedents are applied.",
  "While there cannot be a second opinion that the object behind introducing Section 173(8) into the Code was to achieve a fair, full and complete investigation to excavate the truth, and that, through the years since its introduction, it has served as a boon in the administration of criminal justice, I only fondly hope that a larger Bench of the Supreme Court would overturn these judgments in Reeta Nag & Amrutbhai Patel, which have held a view that, in my opinion, does not promote the legislative intent of Section 173(8) Cr.P.C., and proclaim the correct law.",
];

export default function Blog003Page() {
  return (
    <>
      <Header />

      <section className={styles.heroBanner}>
        <h1 className={styles.heroTitle}>LEGAL UPDATES & BLOG</h1>
        <p className={styles.heroLabel}>Legal Landscape: Recent Developments</p>
      </section>

      <main className={styles.page}>
        <article className={styles.article}>
          <Link href="/legalupdates?type=blog#blog-section" className={styles.backLink}>
            ← Back to Blogs
          </Link>
          <h1>Part - II : The Correct View on S. 173(8) Cr.P.C</h1>

          {paragraphs.map((paragraph, index) => (
            <p key={`blog-003-paragraph-${index}`}>{paragraph}</p>
          ))}
        </article>
      </main>
    </>
  );
}